from Algorithms import Voronoi_algorithm
from Algorithms import Energy_conservative_thinning_algorithm
from Algorithms import k_means_clustering_algorithm
from Algorithms import k_means_merge_average_algorithm
from Algorithms import Leveling_thinning_algorithm
from Algorithms import Number_conservative_thinning_algorithm
from Algorithms import Random_thinning_algorithm
from Algorithms import Vranic_algorithm
